version: "2"

services:

  doorknocker:
    container_name: doorknocker
    build:
      dockerfile: ./bedrock-server/dockerfiles/doorknocker
      context: .
    image: doorknocker:latest
    stdin_open: true
    tty: true
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    restart: always
    volumes:
      - /mnt/efs:/mnt/efs
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /aws/ec2/minecraft-bedrock-server
        awslogs-stream: doorknocker-nginx
        awslogs-create-group: "false" # CloudFormation handles this

  daemon:
    container_name: daemon
    build:
      dockerfile: ./bedrock-server/dockerfiles/daemon
      context: .
    image: daemon:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /mnt/efs:/mnt/efs
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /aws/ec2/minecraft-bedrock-server
        awslogs-stream: doorknocker-daemon
        awslogs-create-group: "false" # CloudFormation handles this
