- hosts: bedrock_server
  become: yes
  tasks:

    - name: Install CloudWatch Logs Agent
      apt:
        deb: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

    - name: Install core system tools
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
          - python3-pip
          - python3-setuptools
          - python3-venv
          - nmap
          - tar
          - zip
          - unzip
          - awscli
          - conspy
        state: latest

    - name: Download Bedrock Server
      unarchive:
        remote_src: yes
        src: https://minecraft.azureedge.net/bin-linux/bedrock-server-{{ bedrock_version }}.zip
        dest: /root

    - name: Copy up files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: './cw-agent-cfg.json'
          dest: '/root/cw-agent-cfg.json'
        # - src: './bedrock-server-logs.service'
        #   dest: '/etc/systemd/system/bedrock-server-logs.service'
        - src: './start-logs-agent.sh'
          dest: '/root/start-logs-agent.sh'
        - src: './bedrock-server.service'
          dest: '/etc/systemd/system/bedrock-server.service'
        - src: './server.properties'
          dest: '/root/server.properties'
        - src: './permissions.json'
          dest: '/root/permissions.json'
        - src: './whitelist.json'
          dest: '/root/whitelist.json'
        - src: './backup-to-s3.sh'
          dest: '/root/backup-to-s3.sh'
        - src: './restore-from-s3.sh'
          dest: '/root/restore-from-s3.sh'

    - name: Set up backup cron job on host
      cron:
        name: "Backup Minecraft Bedrock server data"
        minute: "0"
        hour: "0"
        day: "*/1"
        job: "bash /root/backup-to-s3.sh >> /root/cron.log 2>&1"

    - name: Set up log removal cron job on host
      cron:
        name: "Remove Bedrock server log file, so systemd logging keeps working"
        special_time: reboot
        job: "rm -rf /root/bedrock-server.log"

    - name: Start CloudWatch Logs Agent
      command: bash /root/start-logs-agent.sh

    - name: Check if backup data exists in S3, and retrieve it if so
      command: bash /root/restore-from-s3.sh

    - name: Try to remove log file, so it's opened reliably by the Bedrock Server service
      file:
        path: /root/bedrock-server.log
        state: absent

    - name: Configure & run Bedrock server as a systemd service
      systemd:
        service: bedrock-server.service
        state: restarted
        daemon_reload: yes
        enabled: yes
