- hosts: phantom_proxy
  become: yes
  tasks:

    - name: Copy up .service file
      copy:
        src: "./phantom-proxy.service"
        dest: "/etc/systemd/system/phantom-proxy.service"
        mode: "0644"

    - name: Download Phantom
      get_url:
        url: https://github.com/jhead/phantom/releases/download/v{{ phantom_proxy_version }}/phantom-{{ phantom_proxy_arch }}
        dest: /root/phantom
        mode: '0755'
        force: yes

    - name: Start Phantom proxy service, and enable at boot
      systemd:
        name: phantom-proxy
        state: restarted
        daemon_reload: yes
        enabled: yes
