AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance for Minecraft Bedrock server"
Resources:
  EC2InstanceMain:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-064efdb82ae15e93f" # Latest Ubuntu 18.04 in ca-central-1; https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t2.micro
      KeyName: {{ config.ec2_key_name }}
      SecurityGroupIds:
        - !ImportValue securityGroups-SecurityGroupSSH
        - !ImportValue securityGroups-SecurityGroupMinecraftServer
      SubnetId: !ImportValue vpc-PublicSubnetID
      Tags:
        - Key:   "Name"
          Value: "minecraft-bedrock-server"
