- hosts: bedrock_server
  become: yes
  tasks:

    - name: Install core system tools
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
          - python3-pip
          - python3-setuptools
          - python3-venv
          - nmap
          - tar
          - zip
          - unzip
          - awscli
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-compose
        state: latest

    - name: Add ubuntu user to docker group, for interactive convenience
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Copy up Docker files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: './bedrock-server/Dockerfile', dest: '/root/Dockerfile'}
        - {src: './bedrock-server/docker-compose.yaml', dest: '/root/docker-compose.yaml'}
        - {src: './bedrock-server/server.properties', dest: '/root/server.properties'}
        - {src: './bedrock-server/permissions.json', dest: '/root/permissions.json'}
        - {src: './bedrock-server/whitelist.json', dest: '/root/whitelist.json'}
        - {src: './bedrock-server/backup-to-s3.sh', dest: '/root/backup-to-s3.sh'}
        - {src: './bedrock-server/restore-from-s3.sh', dest: '/root/restore-from-s3.sh'}

    - name: Check if backup data exists, and use it if so
      command: bash /root/restore-from-s3.sh

    - name: Deploy Minecraft Bedrock server
      docker_compose:
        project_src: /root
        build: yes
        recreate: always

    - name: Set up backup cron job on host
      cron:
        name: "Backup Minecraft Bedrock server data"
        minute: "*/15"
        job: "bash /root/backup-to-s3.sh"
