- hosts: minecraft_bedrock_server
  become: yes
  tasks:

    - name: Install core system tools
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
          - python3-pip
          - python3-setuptools
          - python3-venv
          - tar
          - zip
          - unzip
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-compose
        state: latest

    - name: Copy up Dockerfile
      copy:
        src: ./docker/Dockerfile
        dest: /root/Dockerfile
    
    - name: Copy up docker-compose.yaml
      copy:
        src: ./docker/docker-compose.yaml
        dest: /root/docker-compose.yaml

    - name: Deploy Minecraft Bedrock server
      command: docker-compose -f /root/docker-compose.yaml up -d --build

    - name: Set up backup cron job
      cron:
        name: "Backup Minecraft Bedrock server data"
        hour: "3"
        job: "cd /root && tar -czf bedrock_server_backup.tar.gz worlds"
